config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  # root "posts#index"
  root "homes#index"
  resources :contacts, only: %i[index create]

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    registrations: "users/registrations",
    passwords: "users/passwords"
  }
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

  resources :users, only: [:new, :show, :edit, :update] do
    member do
      get "likes"
    end
  end
  get "/mypage", to: "users#mypage"
  resources :statuses

  resources :posts do
    resources :comments, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy]
    resource :like_comments, only: [:create, :destroy]
  end

  resources :hashtags do
    get "posts", to: "posts#search"
  end
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  has_one :status, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  has_many :like_comments, dependent: :destroy
  has_many :liked_comments, through: :like_comments, source: :comment
  accepts_nested_attributes_for :status, allow_destroy: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  def self.guest
    find_or_create_by!(email: "guest@example.com") do |user|
      user.password = SecureRandom.urlsafe_base64
      user.nickname = "ゲストユーザー"
    end
  end
end

app/controllers/users/passwords_controller.rb
module Users
  class PasswordsController < Devise::PasswordsController
    before_action :ensure_normal_user, only: :create

    def ensure_normal_user
      redirect_to new_user_session_path, alert: "ゲストユーザーのパスワード再設定はできません。" if params[:user][:email].casecmp("guest@example.com").zero?
    end

    def create; end
  end
end

app/controllers/users/registrations_controller.rb
module Users
  class RegistrationsController < Devise::RegistrationsController
    before_action :ensure_normal_user, only: %i[update destroy]

    def ensure_normal_user
      redirect_to root_path, alert: "ゲストユーザーの更新・削除はできません。" if resource.email == "guest@example.com"
    end

    def create
      super
      resource.build_status
      resource.save
    end

    def update; end

    def destroy; end
  end
end

app/controllers/users/sessions_controller.rb
module Users
  class SessionsController < Devise::SessionsController
    def guest_sign_in
      guest_user = User.guest
      Status.find_or_create_by!(user_id: guest_user.id)
      sign_in guest_user
      redirect_to root_path, notice: "ゲストユーザーとしてログインしました。"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:mypage, :edit, :update]
  before_action :set_user, only: [:show, :edit, :update]

  def show
    @posts = Post.where(user_id: current_user.id).page(params[:page]).per(9).order(created_at: :desc)
    @statuses = Status.where(user_id: current_user.id)
    likes = Like.where(user_id: current_user.id).pluck(:post_id)
    like_posts = Post.find(likes)
    @like_posts = Kaminari.paginate_array(like_posts).page(params[:page]).per(9)
  end

  def edit
    redirect_to user_path(@user) unless @user == current_user
  end

  def create
    redirect_to user_path(@user), notice: "成功しました"
  end

  def update
    if current_user.update!(user_params)
      redirect_to user_path(current_user), notice: "更新しました"
    else
      redirect_to edit_user_path(current_user), notice: "更新できませんでした"
    end
  end

  def mypage
    redirect_to user_path(current_user)
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.fetch(:user, {}).permit(:nicknamem, :avatar)
  end
end

app/views/users/_form.html.erb
<div class="d-flex justify-content-center">
  <%= form_with model: @user, local: true do |form| %>
    <%= form.file_field :avatar, accept: "image/png,image/jpeg,image/gif" %>
    <%= form.submit "画像を変更", class: "btn btn-primary btn-block mt-4" %>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="base-content">
  <h2 class="text-center">ニックネームの編集</h2>
<div class="d-flex justify-content-center mt-5">
  <%= form_with model: @user, local: true do |f| %>
    <div class="form-group">
      <%= f.label :nickname %>
      <%= f.text_field :nickname, class: "form-control", rows: 1, required: true, maxlength: 30 %>
    </div>
    <%= f.submit "変更", class: "btn btn-primary btn-block mt-5" %>
  <% end %>
</div>

</div>

app/views/users/show.html.erb
<div class="base-content">
  <% if user_signed_in? && @user == current_user %>
    <h1 class="text-center">マイページ</h1>
    <p class="text-center">(<%= @user.nickname %>)<%= link_to "変更", edit_user_path(current_user), class: "badge badge-primary" %></p>
  <% else %>
    <h1 class="text-center">ユーザーページ</h1>
    <p class="text-center">(<%= @user.nickname %>)</p>
  <% end %>


  <div class="row">
    <div class="col-md-6 mt-5">
      <h3 class="text-center">アバター画像</h3>
      <div class="d-flex justify-content-center"><%= image_tag @user.avatar.url, class: "rounded-circle mt-1" %></div>
      <% if user_signed_in? && @user == current_user %>
        <%= render "form" %>
      <% end %>
    </div>
    <div class="col-md-6 mt-5">
      <h3 class="text-center col-md-12">公開中のステータス</h3>
      <% @statuses.each do |status| %>
        <table>
          <tr>
            <td width=40>性別</td>
            <td><%= status.sex_i18n %></td>
          </tr>
          <tr>
            <td>年齢</td>
            <td><%= status.age_i18n %></td>
          </tr>
          <tr>
            <td>身長</td>
            <td><%= status.height_i18n %></td>
          </tr>
          <tr>
            <td>体重</td>
            <td><%= status.weight_i18n %></td>
          </tr>
          <tr>
            <td>体型</td>
            <td><%= status.body_type_i18n %></td>
          </tr>
          <tr>
            <td>食事</td>
            <td><%= status.meal_i18n %></td>
          </tr>
          <tr>
            <td>運動</td>
            <td><%= status.movement_i18n %></td>
          </tr>
          <tr>
            <td>睡眠</td>
            <td><%= status.sleep_i18n %></td>
          </tr>
          <tr>
            <td>環境</td>
            <td><%= status.environment_i18n %></td>
          </tr>
          <tr>
            <td>年収</td>
            <td><%= status.annual_income_i18n %></td>
          </tr>
        </table>
      <% end %>
      <%# btnの高さが揃わない %>
      <div class="d-flex justify-content-center mt-4 pt-1">
        <% if user_signed_in? && @user == current_user %>
          <% if @statuses.blank? %>
            <%= link_to "作成", new_status_path(current_user), class: "btn btn-primary btn-block" %>
          <% else %>
            <%= link_to "変更", edit_status_path(current_user), class: "btn btn-primary btn-block" %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <hr>

  <div class="mt-5">
    <h3 class="mt-5">いいね一覧</h3>
    <div class="row">
      <%= render @like_posts %>
    </div>
    <div class="d-flex justify-content-center">
      <%= paginate @like_posts %>
    </div>

    <hr>
    <h3 class="mt-5">投稿一覧</h3>
    <div class="row">
      <%= render @posts %>
    </div>
    <div class="d-flex justify-content-center">
      <%= paginate @posts %>
    </div>
    <hr>
  </div>
</div>