config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  # root "posts#index"
  root "homes#index"
  resources :contacts, only: %i[index create]

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    registrations: "users/registrations",
    passwords: "users/passwords"
  }
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

  resources :users, only: [:new, :show, :edit, :update] do
    member do
      get "likes"
    end
  end
  get "/mypage", to: "users#mypage"
  resources :statuses

  resources :posts do
    resources :comments, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy]
    resource :like_comments, only: [:create, :destroy]
  end

  resources :hashtags do
    get "posts", to: "posts#search"
  end
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { maximum: 30 }
  validates :content, presence: true, length: { maximum: 500 }
  mount_uploader :image, ImageUploader

  belongs_to :user
  has_many :ingredients, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :graphs, dependent: :destroy
  has_many :hashtag_maps, dependent: :destroy
  has_many :hashtags, through: :hashtag_maps
  has_many :comments, dependent: :destroy
  accepts_nested_attributes_for :ingredients, :graphs, allow_destroy: true

  def liked_by?(user)
    likes.any? { |like| like.user_id == user.id }
  end

  def save_tag(sent_tags)
    current_tags = hashtags.pluck(:hashname) unless hashtags.nil?
    old_tags = current_tags - sent_tags
    new_tags = sent_tags - current_tags

    old_tags.each do |old|
      hashtags.destroy Hashtag.find_by(hashname: old)
    end

    new_tags.each do |new|
      new_post_tag = Hashtag.find_or_create_by(hashname: new)
      hashtags << new_post_tag
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[edit update destroy]
  before_action :hashtag, only: %i[index]

  def index
    @posts = Post.includes(:user, :likes).page(params[:page]).per(12).order(created_at: :desc)
    @tag_list = Hashtag.includes(:posts).order("char_length(hashname) asc").first(300)
    @pickup_tags = Hashtag.includes(:posts).sort { |a, b| b.hashtag_maps.size <=> a.hashtag_maps.size }
  end

  def new
    @post = Post.new
    @ingredients = @post.ingredients.build
    @graphs = @post.graphs.build
  end

  def create
    @post = current_user.posts.new(post_params)
    tag_list = params[:post][:hashname].split(/[[:blank:]]/)
    if @post.save
      @post.save_tag(tag_list)
      redirect_to @post, notice: "投稿しました"
    else
      flash.now[:alert] = "投稿に失敗しました"
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
    @post_tags = @post.hashtags
    @comments = @post.comments
    @comment = current_user.comments.new
    @ingredients = @post.ingredients
    gon.chart_label = ["心", "身体", "睡眠", "集中力", "社会", "お金"]
    gon.chart_data = @post.graphs.pluck(:graph_a, :graph_b, :graph_c, :graph_d, :graph_e, :graph_f).flatten
    @statuses = Status.where(user_id: @post.user.id)
  end

  def edit
    @post = Post.find(params[:id])
    @tag_list = @post.hashtags.pluck(:hashname).join(" ")
  end

  def update
    tag_list = params[:post][:hashname].split(/[[:blank:]]/)
    if @post.update(post_params)
      @post.save_tag(tag_list)
      redirect_to @post, notice: "更新しました"
    else
      flash.now[:alert] = "更新に失敗しました"
      render :edit
    end
  end

  def destroy
    @post.destroy!
    redirect_to posts_path, alert: "削除しました"
  end

  def search
    @tag_list = Hashtag.all
    @tag = Hashtag.find(params[:hashtag_id])
    @posts = @tag.posts.all
  end

  def hashtag
    @user = current_user
    unless params[:name].nil?
      @hashtag = Hashtag.find_by(hashname: params[:name])
      @posts = @hashtag.posts.page(params[:page]).per(20).reverse_order
    end
    @hashtags = Hashtag.all.to_a.group_by { |hashtag| hashtag.posts.count }
  end

  private

  def set_post
    @post = current_user.posts.find_by(id: params[:id])
    redirect_to root_path, alert: "権限がありません" if @post.nil?
  end

  def post_params
    params.require(:post).permit(:title, :image, :content, :tag_name, :user_id,
                                 ingredients_attributes: [:id, :ing_name, :quantity, :explanation, :_destroy],
                                 graphs_attributes: [:id, :graph_a, :graph_b, :graph_c, :graph_d, :graph_e, :graph_f, :_destroy])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_dislike.html.erb
<%= link_to post_likes_path(post), method: :post, class: "btn btn-outline-primary", remote: true do %>
<i class="far fa-heart"></i>
<%= post.likes_count %>
<% end %>

app/views/posts/_dislike_comment.html.erb
<%= link_to post_like_comments_path(comment), method: :post, class: "btn btn-outline-primary", remote: true do %>
  <i class="far fa-heart"></i>
  <%= comment.likes_count %>
<% end %>

app/views/posts/_form.html.erb
<%= render "layouts/error_messages" %>
<%= form_with model: @post, local: true do |f| %>
  <div class="form-group mt-5 col-12">
    <%= f.label :title, class: "h3" %>
    <%= f.text_field :title, class: "form-control form-control-lg", required: true, maxlength: 30, placeholder: "例）頭痛の起こし方、3日坊主の作り方、不安の作り方" %>
  </div>

  <div class="form-group mt-5 col-12">
    <%= f.label :thumbnail, class: "h3" %>
    <%= f.file_field :image, accept: "image/png,image/jpeg,image/gif", class: "form-control-file" %>
  </div>

  <div class="my-2 mt-5 col-12">
    <div class="post my-2">
      <div class="ingredients">
        <div class="mx-auto">
          <%= f.label :ing_name, class: "h3" %>
          <%= f.fields_for :ingredients do |t| %>
            <%= render "posts/ingredient_fields", f: t %>
          <% end %>
        </div>

        <div id="detail-association-insertion-point1"></div>
        
        <div class="col-10 mx-auto mt-2" id="detail-association-insertion-point2">
          <%= link_to_add_association f, :ingredients,
          class: "btn btn-secondary btn-block",
          data: {
          association_insertion_node: '#detail-association-insertion-point1',
          association_insertion_method: 'append'
          } do %>
            <i class="far fa-plus-square"></i>
            <span class="d-none d-md-inline"> レシピを追加</span>
          <% end %>
        </div>
      </div>
    </div>

  <div class="form-group col-12">
    <%= f.label :content, class: "h3 mt-5" %>
    <%= f.text_area :content, class: "form-control", rows: 5, required: true, maxlength: 500, placeholder: "発見経緯、補足情報、詳細説明など書いてみてね" %>
  </div>

  <div class="form-group col-12">
    <%= f.label :hashname, class: "h3 mt-5" %>
    <%= f.text_area :hashname, value: @tag_list,class: "form-control", rows: 1, required: true, maxlength: 36, placeholder: "例）コーヒー 頭痛 吐き気" %>
  </div>
  
  <div class="row my-5">
    <div class="chart-container col-md-6 mx-auto my-auto2">
      <canvas id="myChart"></canvas>
    </div>
    <div class="slidecontainer col-md-4 mx-auto my-auto" id="sliders">
      <%= f.fields_for :graphs do |graph| %>
        <div class="form-group">
          <%= graph.label :graph_a %>
          <%= graph.range_field :graph_a, in: 0..4, list: "tickmarks", class: "slider form-control-range", id: "slider_a"%>
          <span id="val_a">0</span>
        </div>
        <div class="form-group">
          <%= graph.label :graph_b %>
          <%= graph.range_field :graph_b, in: 0..4, list: "tickmarks", class: "slider form-control-range", id: "slider_b" %>
          <span id="val_b">0</span>
        </div>
        <div class="form-group">
          <%= graph.label :graph_c %>
          <%= graph.range_field :graph_c, in: 0..4, list: "tickmarks", class: "slider form-control-range", id: "slider_c" %>
          <span id="val_c">0</span>
        </div>
        <div class="form-group">
          <%= graph.label :graph_d %>
          <%= graph.range_field :graph_d, in: 0..4, list: "tickmarks", class: "slider form-control-range", id: "slider_d" %>
          <span id="val_d">0</span>
        </div>
        <div class="form-group">
          <%= graph.label :graph_e %>
          <%= graph.range_field :graph_e, in: 0..4, list: "tickmarks", class: "slider form-control-range", id: "slider_e" %>
          <span id="val_e">0</span>
        </div>
        <div class="form-group">
          <%= graph.label :graph_f %>
          <%= graph.range_field :graph_f, in: 0..4, list: "tickmarks", class: "slider form-control-range", id: "slider_f" %>
          <span id="val_f">0</span>
        </div>
        <datalist id="tickmarks">
          <option value="0"></option>
          <option value="1"></option>
          <option value="2"></option>
          <option value="3"></option>
          <option value="4"></option>
          <option value="5"></option>
        </datalist>
      <% end %>
    </div>
  </div>
  <%= f.submit class: "btn btn-primary btn-block btn-lg mb-5" %>
<% end %>
<%= javascript_pack_tag 'form_graph', 'data-turbolinks-track': 'reload' %>

app/views/posts/_hashtag_list.html.erb
<h3 class="text-center">注目のタグ</h3>
<% @pickup_tags.first(10).each do |tag| %>
  <div class= "hashtag-name d-inline-flex flex-wrap">
    <span class="mx-2">
        <%= link_to "#{tag.hashname} (#{tag.posts.count})", hashtag_posts_path(hashtag_id: tag.id), data: {"turbolinks" => false} %>
    </span>
  </div>
<% end %>

<button type="button" class="btn btn-primary btn-sm btn-block w-50 mt-3 d-block mx-auto" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
    すべてのタグを開く
</button>
<div class="collapse" id="collapseExample">
    <div class="border p-3">
        <div class= "hashtag-name d-inline-flex flex-wrap">
            <% @tag_list.each do |list| %>
                <span class="mx-2">
                    <%= link_to "#{list.hashname} (#{list.posts.count})", hashtag_posts_path(hashtag_id: list.id), data: {"turbolinks" => false} %>
                </span>
            <% end %>
        </div>
    </div>
</div>

<hr>

app/views/posts/_ingredient_fields.html.erb
<div class="nested-fields mt-3" id="detail-association-insertion-point1">
  <div class="row">
    <div class="col-1 my-auto">
      <%= link_to_remove_association f, class: "btn btn-secondary" do %>
        <i class="fas fa-trash-alt"></i> 
      <% end %>
    </div>
    <div class="offset-md-1 row">
      <div class="form-group col-md-6">
        <%= f.label :ing_name %>
        <%= f.text_field :ing_name, class: "form-control", placeholder: "例）コーヒー" %>
      </div>
      <div class="form-group col-md-3 offset-md-1">
        <%= f.label :quantity %>
        <%= f.text_field :quantity, class: "form-control", placeholder: "例）1日６杯以上" %>
      </div>
      <div class="form-group col-md-12">
        <%= f.label :explanation %>
        <%= f.text_field :explanation, class: "form-control", placeholder: "例）胃に負担をかけるのがポイント" %>
      </div>
    </div>
  </div>
  <hr>
</div>

app/views/posts/_like.html.erb
<%= link_to post_likes_path(post), method: :delete, class: "btn btn-primary", remote: true do %>
<i class="fas fa-heart"></i>
<%= post.likes_count %>
<% end %>

app/views/posts/_like_comment.html.erb
<%= link_to post_like_comments_path(comment), method: :delete, class: "btn btn-primary", remote: true do %>
<i class="fas fa-heart"></i>
  <%= comment.likes_count %>
<% end %>

app/views/posts/_post.html.erb
<div class="my-3 col-md-3">
  <div class="card">
    <div class="d-flex justify-content-between">
      <% if current_user == nil %>
      <% else %>
        <div>
          <% if current_user.id == post.user_id %>
            <%= link_to edit_post_path(post), class: "btn btn-success", data: {"turbolinks" => false } do %>
              <i class="far fa-edit"></i> <span class="d-none d-md-inline"> 編集</span>
            <% end %>
            <%= link_to post, method: :delete, data: { confirm: "削除しますか?" }, class: "btn btn-danger" do %>
              <i class="far fa-trash-alt"></i> <span class="d-none d-md-inline"> 削除</span>
            <% end %>          
          <% end %>
        </div>
        <div id="post-<%= post.id %>">
          <% if post.liked_by?(current_user) %>
            <%= render "posts/like", post: post %>
          <% else %>
            <%= render "posts/dislike", post: post %>
          <% end %>
        </div>
      <% end %>
    </div>
    
    <%= link_to post, class: "card-img-top", "data-turbolinks": false, data: {"turbolinks"=>false} do %>
      <%= image_tag post.image.thumb.url, class: "bd-placeholder-img card-img-top" %>
    <% end %>
    
    <h4 class="card-title"><%= post.title %></h4>
    
    <div class= "hashtag-name d-inline-flex flex-wrap">
        <% post.hashtags.first(3).each do |tag| %>
            <span class="mx-2">
                <%= link_to "#{tag.hashname}", hashtag_posts_path(hashtag_id: tag.id), data: {"turbolinks" => false} %>
            </span>
        <% end %>
    </div>
    <%= link_to user_path(post.user.id), class: "mt-3 text-left" do %>
      <%= post.user.nickname.present? ? "投稿者： #{post.user.nickname}" : "投稿No.#{post.user.id}" %>
    <% end %>
  </div>
</div>

app/views/posts/_status.html.erb
 <% @statuses.each do |status| %>
  <p>
    性別:<%= status.sex_i18n %>
  <br>
    年齢:<%= status.age_i18n %>
  <br>
    身長:<%= status.height_i18n %>
  <br>
    体重:<%= status.weight_i18n %>
  <br>
    体型:<%= status.body_type_i18n %>
  <br>
    食事:<%= status.meal_i18n %>
  <br>
    運動:<%= status.movement_i18n %>
  <br>
    睡眠:<%= status.sleep_i18n %>
  <br>
    環境:<%= status.environment_i18n %>
  <br>
    年収:<%= status.annual_income_i18n %>
  </P>
<% end %>

app/views/posts/edit.html.erb
<div class="base-content">
  <h1>レシピの編集</h1>
  <%= render "form" %>
</div>

app/views/posts/index.html.erb
<div class="base-content">
  <%= render "hashtag_list" %>
  <h1 class="text-center mt-5">レシピの一覧</h1>
  <div class="d-flex justify-content-center mt-5">
    <%= paginate @posts %>
  </div>
  <div class="row mt-3">
    <%= render @posts %>
  </div>
  <div class="d-flex justify-content-center mt-5">
    <%= paginate @posts %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="base-content">
  <h1 class="text-center">レシピを書く</h1>
  <%= render "form" %>
</div>

app/views/posts/search.html.erb
<div class="base-content">
  <h1 class="text-center">
    <%= "#{@tag.hashname}" %>
    <%= " の投稿一覧" %>
  </h1>

  <br>
  <div class="row">
    <%= render @posts%>
  </div>
</div>

app/views/posts/show.html.erb
<div class="base-content">
  <h1 class="text-center">レシピの詳細</h1>

  <section class="card border-dark">
    <div class="card-header d-flex justify-content-between">
      <div id="post-<%= @post.id %>">
        <% if @post.liked_by?(current_user) %>
          <%= render "like", post: @post %>
        <% else %>
          <%= render "dislike", post: @post %>
        <% end %>
      </div>
      <div>
        <% if current_user.id == @post.user_id %>
            <%= link_to "編集", edit_post_path(@post), class: "btn btn-success", data: {"turbolinks" => false } %>
            <%= link_to "削除", post_path(@post), method: :delete, class: "btn btn-danger", data: { confirm: "削除しますか？" } %>
        <% end %>
      </div>
    </div>

    <div class= "hashtag-name d-inline-flex flex-wrap">
      <% @post_tags.each do |tag| %>
        <span class="mx-2">
          <%= link_to "#{tag.hashname} (#{tag.posts.count})", hashtag_posts_path(hashtag_id: tag.id) %>
        </span>
      <% end %>
    </div>

    <strong class="card-title h1 text-center mt-5"><%= @post.title %></strong>
    <hr>
    <div class="row container-fluid d-flex justify-content-around">
      <div class="card-body col-md-5">
        <%= image_tag @post.image.url, class: "img-fluid" %>
      </div>

      <div class="card-body col-md-5">
        <h3 class="text-tile h2">レシピ</h3>
        <ol class="mt-3">
        <% @ingredients.each do |ing| %>
          <div class="h4">
            <li>
              <span class="d-inline-block"><%= ing.ing_name %></span>
              <span class="d-inline-block">(<%= ing.quantity %>)</span>
            </li>
          </div>
          <div class="offset-1">
            <%= ing.explanation %>
          </div>
          <hr>
        <% end %>
        </ol>
      </div>

      <div class="card-body col-md-5 mt-5">
        <h3 class="h2">レシピ情報</h3>
        <p class="p-3 mb-2 bg-light text-dark">
        <%= @post.content %>
        </p>
      </div>
      
      <div class="card-body col-md-5 mt-5">
        <div class="chart-container mt-5">
          <canvas id="radar-chart" ></canvas>
        </div>
      </div>
    </div>

    <div class="card-footer d-inline-flex justify-content-between align-items-end flex-wrap">
      <div>
        <%= link_to user_path(@post.user.id) do %>
          <%= image_tag @post.user.avatar.thumb.url, class: "rounded-circle" %>
          <%= @post.user.nickname %>
        <% end %>
      </div>
      <div>
        <small class="text-secondary">
          <%= "投稿日時 : #{l @post.created_at}" %> 
          <br>
          <%= "更新日時 : #{l @post.updated_at}" %>
        </small>
      </div>
    </div>
  </section>

  <div class="base-container mt-5" >
    <h2>コメント一覧</h2>
    <% @comments.each do |comment| %>
      <div>
        <div class="balloon1-left">
          <%= simple_format(comment.content) %>
        </div>
      </div>
      <div class="d-inline-flex">
        <div>
          <%= link_to user_path(@post.user.id) do %>
            <%= image_tag comment.user.avatar.thumb.url, class: "rounded-circle" %>
            <%= comment.user.nickname.present? ? "#{comment.user.nickname}" : "投稿No.#{comment.user.id}" %>
          <% end %>
        </div>
        <div id="comment-<%= comment.id %>" class="mx-2 align-self-center">
          <% if comment.liked_by?(current_user) %>
            <%= render "like_comment", comment: comment %>
          <% else %>
            <%= render "dislike_comment", comment: comment %>
          <% end %>
        </div>
        <div  class="mx-2 align-self-center">
          <% if current_user.id == comment.user_id %>
            <%= link_to post_comment_path(comment), method: :delete, data: { confirm: "削除しますか?" }, class: "btn btn-danger" do %>
              <i class="far fa-trash-alt"></i> <span class="d-none d-md-inline"> 削除</span>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <hr>
  <div class="base-container mb-5" >
    <h2 class="mt-5">コメントする</h2>
    <%= form_with(model:[@post, @comment], method: :post) do |f| %>
      <%= f.text_area :content %>
      <%= f.hidden_field :post_id, value: @post.id %>
      <br>
      <%= f.submit '書き込む' %>
    <% end %>
  </div>
  <%= javascript_pack_tag 'graph', 'data-turbolinks-track': 'reload' %>
</div>