config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  # root "posts#index"
  root "homes#index"
  resources :contacts, only: %i[index create]

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    registrations: "users/registrations",
    passwords: "users/passwords"
  }
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

  resources :users, only: [:new, :show, :edit, :update] do
    member do
      get "likes"
    end
  end
  get "/mypage", to: "users#mypage"
  resources :statuses

  resources :posts do
    resources :comments, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy]
    resource :like_comments, only: [:create, :destroy]
  end

  resources :hashtags do
    get "posts", to: "posts#search"
  end
end

app/views/layouts/_error_messages.html.erb
<% if @post.errors.any? %>
  <% @post.errors.full_messages.each do |msg| %>
    <div class="alert alert-danger" role="alert">
      <a href="#" class="close" data-dismiss="alert">×</a>
      <%= msg %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |flash_type, msg| %>
  <div class="alert alert-<%= flash_type %> margin-cancell flash-window hidden" role="alert">
    <a href="#" class="close flash-window--delete mx-3" data-dismiss="alert">x</a>
    <%= msg %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<nav>
  <small class="text-white">&copy; 2022 Fukenkou Recipe</small>
</nav>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-sm navbar-dark background-color fixed-top">
  <div class="base-container justify-content-around">
    <%= link_to root_path, class: "justify-content-start", data: {"turbolinks" => false } do %>
      <%= image_tag 'logo2.png', class: "logo", alt: "不健康レシピ" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNavAltMarkup">
      <div class="navbar-nav", data-turbolinks='false'>
        <% if user_signed_in? %>
          <%= link_to "トップ", posts_path, class: "nav-item nav-link active my-auto" %>
          <%= link_to "レシピを書く", new_post_path, class: "nav-item nav-link active my-auto"%>
          <%= link_to 'マイページ', mypage_path, class: "nav-item nav-link active my-auto" %>
          <%= link_to "アカウント編集", edit_user_registration_path, class: "nav-item nav-link active my-auto" %>
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, data: { confirm: "ログアウトしますか？" }, class: "nav-item nav-link active my-auto" %>
          <%= link_to "お問い合わせ", "/contacts", class: "nav-item nav-link active my-auto" %>
          <div class="img-responsive center-block text-light">
            <%= image_tag current_user.avatar.thumb.url, class: "rounded-circle" %>
            <%= "#{current_user.nickname}" %>
          </div>
        <% else %>
          <%= link_to "アカウント登録", new_user_registration_path, class: "nav-item nav-link active" %>
          <%= link_to "ログイン", new_user_session_path, class: "nav-item nav-link active" %>
          <%= link_to "ゲストログイン", users_guest_sign_in_path, method: :post, class: "nav-item nav-link active" %>
        <% end %>

      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>不健康レシピ</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'reset', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag('favicon2.png') %>
    <% if flash[:notice] %>
      <%= javascript_pack_tag 'flash_window' %>
    <% end %>
  </head>
  <body>
    <%= Gon::Base.render_data %>
      <header>
        <%= render "layouts/header" %>
      </header>
      <main>
        <div class="base-container main">
        <%= render "layouts/flash" %>
          <%= yield %>
        </div>
      </main>
      <footer class="background-color">
        <%= render "layouts/footer" %>
      </footer>
  </body>
</html>